# Generated by Django 4.1.4 on 2022-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterDataSql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=300, null=True)),
                ('average_wage', models.CharField(blank=True, max_length=300, null=True)),
                ('population', models.CharField(blank=True, max_length=300, null=True)),
                ('hh_size', models.CharField(blank=True, max_length=300, null=True)),
                ('volume', models.CharField(blank=True, max_length=300, null=True)),
                ('total_bill', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'water_data_sql',
                'managed': True,
            },
        ),
    ]
